"""Email notification for compliance results."""

from __future__ import annotations

import smtplib
from email.mime.text import MIMEText

import ai_trace_auditor
from ai_trace_auditor.comply.runner import CompliancePackage


def format_email_body(pkg: CompliancePackage) -> str:
    """Format a CompliancePackage into a plain-text email body."""
    score = pkg.compliance_score
    score_text = f"{score * 100:.1f}%" if score is not None else "N/A (no traces provided)"

    lines = [
        "EU AI Act Compliance Report",
        "=" * 40,
        "",
        f"Source: {pkg.source_dir}",
        f"Compliance Score: {score_text}",
        f"Articles Covered: {', '.join(pkg.articles_covered)}",
        f"Tool: AI Trace Auditor v{ai_trace_auditor.__version__}",
        "",
    ]

    if pkg.gap_report:
        summary = pkg.gap_report.summary
        lines.extend([
            "Results:",
            f"  Satisfied: {summary.satisfied}",
            f"  Partial: {summary.partial}",
            f"  Missing: {summary.missing}",
            f"  N/A: {summary.not_applicable}",
            "",
        ])

        if summary.top_gaps:
            lines.append("Top Gaps:")
            for gap in summary.top_gaps[:5]:
                lines.append(f"  - {gap}")
            lines.append("")

    if pkg.warnings:
        lines.append(f"Warnings ({len(pkg.warnings)}):")
        for w in pkg.warnings:
            lines.append(f"  - {w}")
        lines.append("")

    lines.append("---")
    lines.append("Generated by AI Trace Auditor (https://github.com/BipinRimal314/ai-trace-auditor)")

    return "\n".join(lines)


def send_email_notification(
    to: str,
    pkg: CompliancePackage,
    smtp_host: str = "localhost",
    smtp_port: int = 587,
    smtp_user: str | None = None,
    smtp_password: str | None = None,
    from_addr: str = "aitrace@compliance.local",
    use_tls: bool = True,
    use_ssl: bool = False,
) -> bool:
    """Send compliance results via email.

    Uses Python's built-in smtplib. Returns True on success.

    Args:
        use_tls: Use STARTTLS (port 587). Default True.
        use_ssl: Use implicit SSL (port 465). Mutually exclusive with use_tls.
    """
    import sys

    body = format_email_body(pkg)
    score = pkg.compliance_score
    score_text = f"{score * 100:.0f}%" if score is not None else "pending"

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = f"[AI Trace Auditor] Compliance: {score_text} - {pkg.source_dir}"
    msg["From"] = from_addr
    msg["To"] = to

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=10) as server:
                if smtp_user and smtp_password:
                    server.login(smtp_user, smtp_password)
                server.sendmail(from_addr, [to], msg.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
                server.ehlo()
                if use_tls:
                    server.starttls()
                if smtp_user and smtp_password:
                    server.login(smtp_user, smtp_password)
                server.sendmail(from_addr, [to], msg.as_string())
        return True
    except (smtplib.SMTPException, OSError) as exc:
        print(f"[ai-trace-auditor] Email notification failed: {exc}", file=sys.stderr)
        return False
