"""PDF report generation from Markdown compliance reports.

Uses markdown → HTML → PDF pipeline. Requires optional [pdf] dependency:
    pip install ai-trace-auditor[pdf]
"""

from __future__ import annotations

from pathlib import Path

CSS = """
@page {
    size: A4;
    margin: 2cm;
    @bottom-center { content: counter(page) " / " counter(pages); font-size: 9px; color: #888; }
}
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 11px;
    line-height: 1.6;
    color: #1a1a1a;
}
h1 { font-size: 22px; font-weight: 700; margin: 0 0 16px 0; color: #003d5c; border-bottom: 2px solid #003d5c; padding-bottom: 8px; }
h2 { font-size: 16px; font-weight: 700; margin: 24px 0 12px 0; color: #003d5c; border-bottom: 1px solid #d1d5db; padding-bottom: 6px; }
h3 { font-size: 13px; font-weight: 700; margin: 16px 0 8px 0; color: #1a1a1a; }
p { margin: 0 0 10px 0; }
table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10px; }
th { background: #003d5c; color: white; padding: 6px 10px; text-align: left; font-weight: 600; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
tr:nth-child(even) { background: #f8f9fa; }
code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-family: "SF Mono", Consolas, monospace; font-size: 10px; }
pre { background: #1e1e2e; color: #cdd6f4; padding: 12px; border-radius: 6px; font-size: 10px; line-height: 1.5; overflow-wrap: break-word; white-space: pre-wrap; }
pre code { background: none; color: inherit; padding: 0; }
ul, ol { margin: 8px 0 8px 20px; }
li { margin-bottom: 4px; }
blockquote { border-left: 3px solid #003d5c; padding-left: 12px; margin: 12px 0; color: #4a5568; }
strong { font-weight: 600; }
.header-meta { font-size: 10px; color: #6b7280; margin-bottom: 20px; }
"""

HEADER_HTML = """
<div class="header-meta">
    Generated by AI Trace Auditor | EU AI Act Compliance Report | {date}
</div>
"""


def markdown_to_pdf(markdown_content: str, output_path: Path) -> None:
    """Convert a Markdown compliance report to PDF.

    Requires weasyprint: pip install ai-trace-auditor[pdf]
    """
    try:
        import markdown
    except ImportError as e:
        raise ImportError(
            "PDF generation requires the 'markdown' package. "
            "Install with: pip install ai-trace-auditor[pdf]"
        ) from e

    try:
        from weasyprint import HTML
    except ImportError as e:
        raise ImportError(
            "PDF generation requires 'weasyprint'. "
            "Install with: pip install ai-trace-auditor[pdf]"
        ) from e

    from datetime import datetime, timezone

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Convert Markdown to HTML
    md = markdown.Markdown(extensions=["tables", "fenced_code", "toc"])
    body_html = md.convert(markdown_content)

    # Wrap in full HTML document
    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>{CSS}</style>
</head>
<body>
    {HEADER_HTML.format(date=now)}
    {body_html}
</body>
</html>"""

    # Generate PDF
    HTML(string=html_doc).write_pdf(str(output_path))


def check_pdf_available() -> bool:
    """Check if PDF dependencies are installed."""
    try:
        import markdown  # noqa: F401
        from weasyprint import HTML  # noqa: F401
        return True
    except ImportError:
        return False
